### ISSUE TITLE
Can I call 'next()' in await-style?

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/arc-example-login-flow#3]
With arc 4 using the modern 'URL handlers return a response' style, we can make most URL handlers simply return a response. This repo has an example on: https://github.com/arc-repos/arc-example-login-flow/blob/e8c4b4d2a8a5a70030650693f2b82e72952b9b98/src/http/get-protected/index.js#L6

But how can we do `next()` per [the middleware doc](https://github.com/arc-repos/arc-example-login-flow/blob/e8c4b4d2a8a5a70030650693f2b82e72952b9b98/src/http/get-protected/index.js#L6) , scroll down to 'middleware; using async?

https://github.com/arc-repos/arc-example-login-flow/blob/e8c4b4d2a8a5a70030650693f2b82e72952b9b98/src/http/get-protected/index.js#L6

If there's no way to do `next()` the docs should still make that clear.

**Comment by brianleroux** [comment]
opening in arc-repos/architect repo!
